# Number of days of inactivity before an issue becomes stale
daysUntilStale: 1
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 1
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hi there. There hasn't been activity on this issue in a while. Please confirm that this is still a relevant issue. If it is not, you don't have to do anything and this issue will be closed in 7 days.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false